"""fix: correct dragon data types

Revision ID: 12d16c416333
Revises: 6e5c51fd2c81
Create Date: 2026-08-08 21:24:15.238895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '12d16c416333'
down_revision: Union[str, Sequence[str], None] = '6e5c51fd2c81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_dragons_species'), 'dragons', ['species'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dragons_species'), table_name='dragons')
    # ### end Alembic commands ###
