"""init

Revision ID: 6e5c51fd2c81
Revises: 
Create Date: 2026-08-07 14:07:09.229343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e5c51fd2c81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abilities',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('classes',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_classes_name'), 'classes', ['name'], unique=True)
    op.create_table('distributions',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alternatenames', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('dragons',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('species', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('firetype', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('features', postgresql.ARRAY(sa.TEXT()), nullable=False),
    sa.Column('colors', postgresql.ARRAY(sa.TEXT()), nullable=False),
    sa.Column('diet', postgresql.ARRAY(sa.TEXT()), nullable=False),
    sa.Column('habitat', postgresql.ARRAY(sa.TEXT()), nullable=False),
    sa.Column('size', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('wingspan', sa.Integer(), nullable=False),
    sa.Column('trainable', sa.Boolean(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('armor', sa.Integer(), nullable=False),
    sa.Column('firepower', sa.Integer(), nullable=False),
    sa.Column('shotlimit', sa.Integer(), nullable=False),
    sa.Column('venom', sa.Integer(), nullable=False),
    sa.Column('jawstrength', sa.Integer(), nullable=False),
    sa.Column('class_uid', sa.Uuid(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['class_uid'], ['classes.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('distribution_dragons',
    sa.Column('dragon_uid', sa.Uuid(), nullable=False),
    sa.Column('distribution_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['distribution_uid'], ['distributions.uid'], ),
    sa.ForeignKeyConstraint(['dragon_uid'], ['dragons.uid'], ),
    sa.PrimaryKeyConstraint('dragon_uid', 'distribution_uid')
    )
    op.create_table('dragon_abilities',
    sa.Column('dragon_uid', sa.Uuid(), nullable=False),
    sa.Column('ability_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['ability_uid'], ['abilities.uid'], ),
    sa.ForeignKeyConstraint(['dragon_uid'], ['dragons.uid'], ),
    sa.PrimaryKeyConstraint('dragon_uid', 'ability_uid')
    )
    op.create_table('images',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('dragon_uid', sa.Uuid(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['dragon_uid'], ['dragons.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_table('dragon_abilities')
    op.drop_table('distribution_dragons')
    op.drop_table('dragons')
    op.drop_table('distributions')
    op.drop_index(op.f('ix_classes_name'), table_name='classes')
    op.drop_table('classes')
    op.drop_table('abilities')
    # ### end Alembic commands ###
