"""fix: allow null dragon class icon

Revision ID: 99d0d30d64ae
Revises: 12d16c416333
Create Date: 2026-08-09 00:48:04.719993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '99d0d30d64ae'
down_revision: Union[str, Sequence[str], None] = '12d16c416333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'icon',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'icon',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
